// ============================================================
//  Knowledge Copilot — 6-Level RAG Pipeline (Gemini API)
// ============================================================

const DEMO_DOCUMENT = `
Knowledge Copilot — Technical Reference

## What is RAG?
Retrieval-Augmented Generation (RAG) is a technique that combines information retrieval with language model generation. Instead of relying solely on the model's parametric knowledge, RAG fetches relevant documents at inference time and conditions the answer on that retrieved context. This grounds responses in real data and dramatically reduces hallucinations.

## Level 1: Query Rewriting
Raw user queries are often ambiguous or poorly phrased for retrieval. Query rewriting uses an LLM to expand, clarify, and reformulate the question into a retrieval-optimized form. For example, "what is HyDE?" becomes "Explain Hypothetical Document Embedding (HyDE) technique used in RAG pipelines for improving semantic search quality." This step alone can lift recall by 15–30%.

## Level 2: HyDE (Hypothetical Document Embedding)
HyDE (Hypothetical Document Embedding) is a technique where instead of embedding the query directly, the system first asks the LLM to generate a hypothetical "ideal answer" document, then embeds that hypothetical document for retrieval. The intuition is that the hypothetical answer lives in the same embedding space as real answers, leading to better nearest-neighbor matches. HyDE is especially effective for abstract or domain-specific questions where the query and relevant documents use different vocabulary.

## Level 3: Hybrid Retrieval
Hybrid retrieval combines two complementary signals: dense (semantic) retrieval using vector embeddings and sparse (lexical) retrieval using BM25 or TF-IDF. Dense retrieval excels at semantic similarity — it finds conceptually related content even when exact terms differ. Sparse retrieval excels at exact keyword matching — critical for names, codes, and technical terms. Combining both with Reciprocal Rank Fusion (RRF) produces significantly better recall than either alone. A typical hybrid system achieves 10–25% improvement in recall@10 over pure dense retrieval.

## Level 4: Reranking
After hybrid retrieval, the top-k candidate chunks (typically 20–50) are passed through a cross-encoder reranker. Unlike bi-encoders used for retrieval, cross-encoders jointly process the query and each candidate chunk together, producing a more accurate relevance score. The top 5–10 reranked chunks are then passed to generation. Reranking is computationally expensive but only runs on a small candidate set, making the latency overhead acceptable. Models like Cohere Rerank or a fine-tuned BERT achieve strong performance.

## Level 5: Grounded Generation
The final answer is generated by a large language model conditioned strictly on the retrieved and reranked context. The system prompt instructs the model to only use information from the provided context, cite sources using [1], [2] notation, and explicitly state when information is not available. This grounding step is what separates RAG from open-ended generation — the model cannot hallucinate facts that aren't in the retrieved context.

## Level 6: Faithfulness Verification
After generation, a faithfulness check asks the LLM to evaluate whether each claim in the generated answer is actually supported by the retrieved context. It assigns a confidence score from 0 to 100. Scores above 80 indicate high faithfulness. Scores below 50 flag potential hallucinations for human review. This self-evaluation loop allows the system to surface uncertainty rather than presenting low-confidence answers as fact.

## Chunking Strategy
Effective RAG depends heavily on how documents are split into chunks. Fixed-size chunking (e.g., 512 tokens with 50-token overlap) is simple but often splits semantic units mid-sentence. Semantic chunking uses sentence embeddings to detect topic boundaries and split there instead. Hierarchical chunking maintains parent-child relationships between document sections and paragraphs. The best strategy depends on document type: semantic chunking works best for prose, structural chunking for code and tables.

## Vector Stores
Popular vector databases include Pinecone (managed, production-grade), Weaviate (open-source, schema-aware), Qdrant (open-source, fast), and pgvector (PostgreSQL extension). For small datasets (<100K vectors), in-memory similarity search is sufficient. At scale, approximate nearest neighbor (ANN) algorithms like HNSW provide sub-millisecond retrieval with 95%+ recall.

## Evaluation Metrics
Key RAG metrics: Context Recall — what fraction of relevant information was retrieved? Context Precision — how much of the retrieved context was actually relevant? Answer Faithfulness — are all answer claims supported by context? Answer Relevance — how well does the answer address the original question? The RAGAS framework automates evaluation of all four metrics using an LLM judge.
`;

// ── Utility: cosine similarity ────────────────────────────────
function cosine(a, b) {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) { dot += a[i] * b[i]; na += a[i] ** 2; nb += b[i] ** 2; }
  return dot / (Math.sqrt(na) * Math.sqrt(nb) + 1e-8);
}

// ── Utility: BM25 score ───────────────────────────────────────
function bm25Score(query, doc, avgLen, k1 = 1.5, b = 0.75) {
  const qTerms = query.toLowerCase().split(/\W+/).filter(Boolean);
  const dTerms = doc.toLowerCase().split(/\W+/).filter(Boolean);
  const dLen = dTerms.length;
  const freq = {};
  dTerms.forEach(t => (freq[t] = (freq[t] || 0) + 1));
  let score = 0;
  qTerms.forEach(t => {
    const tf = freq[t] || 0;
    const idf = Math.log((10 + 1) / (tf > 0 ? 1 : 0.5) + 1);
    score += idf * (tf * (k1 + 1)) / (tf + k1 * (1 - b + b * dLen / avgLen));
  });
  return score;
}

// ── Utility: simple embedding (character n-gram TF) ───────────
function simpleEmbed(text, dim = 64) {
  const t = text.toLowerCase();
  const vec = new Float32Array(dim);
  for (let i = 0; i < t.length - 1; i++) {
    const h = ((t.charCodeAt(i) * 31 + t.charCodeAt(i + 1)) * 17) % dim;
    vec[Math.abs(h)] += 1;
  }
  const norm = Math.sqrt(vec.reduce((s, v) => s + v * v, 0)) + 1e-8;
  return Array.from(vec).map(v => v / norm);
}

// ── Semantic chunking ─────────────────────────────────────────
function chunkDocument(text, targetSize = 900, overlap = 120) {
  const normalized = String(text || '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .trim();

  if (!normalized) return [];

  const blankParagraphs = normalized
    .split(/\n\s*\n+/)
    .map(p => p.trim())
    .filter(Boolean);

  let units = blankParagraphs;

  // Fallback for single-paragraph notes, code, and short files.
  if (units.length <= 1) {
    const lines = normalized
      .split(/\n+/)
      .map(line => line.trim())
      .filter(Boolean);

    if (lines.length > 1) {
      units = lines;
    } else {
      units = [normalized];
    }
  }

  const chunks = [];
  let buffer = '';

  const flush = () => {
    const chunk = buffer.trim();
    if (chunk) {
      chunks.push({
        id: chunks.length,
        text: chunk,
        source: `chunk_${chunks.length + 1}`,
      });
    }
    buffer = '';
  };

  for (const unit of units) {
    if (!unit) continue;
    const addition = buffer ? `\n\n${unit}` : unit;

    if ((buffer + addition).length <= targetSize) {
      buffer += addition;
      continue;
    }

    if (buffer) flush();

    // Very long unit: split into overlapping character windows.
    if (unit.length > targetSize) {
      let start = 0;
      while (start < unit.length) {
        const slice = unit.slice(start, start + targetSize).trim();
        if (slice) {
          chunks.push({
            id: chunks.length,
            text: slice,
            source: `chunk_${chunks.length + 1}`,
          });
        }
        start += Math.max(1, targetSize - overlap);
      }
    } else {
      buffer = unit;
    }
  }

  flush();
  return chunks;
}

// ── Document Store ────────────────────────────────────────────
export class DocumentStore {
  constructor() {
    this.chunks = [];
    this.documents = [];
    this.nextDocId = 1;
    this.avgLen = 0;
    this.addDocument('Demo: Knowledge Copilot Reference', DEMO_DOCUMENT);
  }

  recomputeAverageLength() {
    this.avgLen = this.chunks.length
      ? this.chunks.reduce((s, c) => s + c.text.split(/\W+/).length, 0) / this.chunks.length
      : 0;
  }

  getDocuments() {
    return this.documents.map(doc => ({
      id: doc.id,
      name: doc.name,
      chunks: doc.chunks,
    }));
  }

  addDocument(name, text) {
    const docId = this.nextDocId++;
    const newChunks = chunkDocument(text).map(c => ({
      ...c,
      id: `${docId}:${c.id}`,
      docId,
      source: name,
      embedding: simpleEmbed(c.text),
    }));

    this.documents.push({
      id: docId,
      name,
      chunks: newChunks.length,
    });

    this.chunks.push(...newChunks);
    this.recomputeAverageLength();

    return { docId, chunkCount: newChunks.length };
  }

  removeDocument(docId) {
    const numericId = Number(docId);
    this.documents = this.documents.filter(doc => doc.id !== numericId);
    this.chunks = this.chunks.filter(chunk => chunk.docId !== numericId);
    this.recomputeAverageLength();
  }

  search(queryEmb, queryText, topK = 8) {
    if (!this.chunks.length) return [];

    return this.chunks
      .map(c => ({
        ...c,
        denseScore: cosine(queryEmb, c.embedding),
        sparseScore: bm25Score(queryText, c.text, this.avgLen || 1),
      }))
      .map(c => {
        const sourceBoost = c.source === 'Demo: Knowledge Copilot Reference' ? 0 : 0.03;
        return { ...c, hybridScore: 0.6 * c.denseScore + 0.4 * (c.sparseScore / 10) + sourceBoost };
      })
      .sort((a, b) => b.hybridScore - a.hybridScore)
      .slice(0, topK);
  }
}

// ── Gemini API wrapper (non-streaming) ────────────────────────
// ── Gemini API wrapper (non-streaming) ────────────────────────
const GEMINI_MODEL = 'gemini-1.5-flash';

async function callGemini(apiKey, messages, system = '', maxTokens = 1024) {
  // Combine system prompt + last user message into a single prompt
  const lastMsg = messages[messages.length - 1].content;
  const fullPrompt = system ? `${system}\n\n${lastMsg}` : lastMsg;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: fullPrompt }] }],
        generationConfig: { maxOutputTokens: maxTokens },
      }),
    }
  );

  const data = await res.json();
  if (!res.ok) {
    throw new Error(data?.error?.message || `Gemini API error ${res.status}`);
  }
  return data.candidates[0].content.parts[0].text;
}

// ── Gemini API wrapper (streaming) ───────────────────────────
async function callGeminiStream(apiKey, prompt, system = '', maxTokens = 1024, onChunk) {
  const fullPrompt = system ? `${system}\n\n${prompt}` : prompt;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:streamGenerateContent?alt=sse&key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: fullPrompt }] }],
        generationConfig: { maxOutputTokens: maxTokens },
      }),
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.error?.message || `Gemini API error ${res.status}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let fullText = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    const lines = decoder.decode(value).split('\n');
    for (const line of lines) {
      if (line.startsWith('data: ')) {
        try {
          const json = JSON.parse(line.slice(6));
          const chunk = json?.candidates?.[0]?.content?.parts?.[0]?.text;
          if (chunk) {
            fullText += chunk;
            onChunk(fullText);
          }
        } catch {}
      }
    }
  }
  return fullText;
}

// ============================================================
//  6-Level RAG Pipeline
// ============================================================

// Level 1: Query Rewriting
async function level1_queryRewrite(query, apiKey) {
  const rewritten = await callGemini(
    apiKey,
    [{ role: 'user', content: `Rewrite this search query to be more specific and retrieval-optimized. Return ONLY the rewritten query, no explanation:\n\n"${query}"` }],
    'You are a query optimization expert. Expand acronyms, add relevant technical terms, and make the query more specific for semantic search. Output only the rewritten query.',
    256
  );
  return rewritten.trim();
}

// Level 2: HyDE
async function level2_hyde(rewrittenQuery, apiKey) {
  const hypothetical = await callGemini(
    apiKey,
    [{ role: 'user', content: `Write a short 2-3 sentence factual passage that directly answers: "${rewrittenQuery}"\n\nWrite it as if it were an excerpt from a technical documentation page.` }],
    'You are a technical writer. Generate a plausible factual passage that would be a perfect answer to the query. Be specific and technical.',
    300
  );
  return hypothetical.trim();
}

// Level 3: Hybrid Retrieval (done in DocumentStore.search)

// Level 4: Reranking (LLM-based cross-encoder simulation)
async function level4_rerank(query, candidates, apiKey) {
  const list = candidates.slice(0, 6).map((c, i) => `[${i}] ${c.text.slice(0, 200)}...`).join('\n\n');
  const ranking = await callGemini(
    apiKey,
    [{
      role: 'user',
      content: `Query: "${query}"\n\nCandidates:\n${list}\n\nReturn a JSON array of indices sorted by relevance (most relevant first), e.g. [2,0,4,1,3,5]. Return ONLY the JSON array.`
    }],
    'You are a relevance judge. Rank the candidates by how well they answer the query. Return only a JSON array of indices.',
    128
  );
  try {
    const order = JSON.parse(ranking.match(/\[[\d,\s]+\]/)?.[0] || '[0,1,2,3,4,5]');
    return order.map(i => candidates[i]).filter(Boolean);
  } catch {
    return candidates;
  }
}

// Level 5: Grounded Generation (streaming)
async function level5_generate(originalQuery, rerankedChunks, apiKey, onChunk) {
  const context = rerankedChunks.map((c, i) => `[${i + 1}] Source: ${c.source}\n${c.text}`).join('\n\n---\n\n');

  const system = `You are a precise knowledge assistant. Answer questions using ONLY the provided context.
- Cite sources inline as [1], [2] etc. matching the context numbers
- If the answer isn't in the context, say "I don't have information about that in the current knowledge base."
- Be concise and factual. Never fabricate information.`;

  const prompt = `Context:\n${context}\n\nQuestion: ${originalQuery}`;

  return await callGeminiStream(apiKey, prompt, system, 1024, onChunk);
}

// Level 6: Faithfulness Check
async function level6_faithfulness(answer, chunks, apiKey) {
  const context = chunks.map((c, i) => `[${i + 1}] ${c.text.slice(0, 300)}`).join('\n\n');
  const result = await callGemini(
    apiKey,
    [{
      role: 'user',
      content: `Context:\n${context}\n\nAnswer to evaluate:\n${answer}\n\nScore faithfulness 0-100 (how well the answer is supported by context). Return JSON: {"score": <number>, "verdict": "<one sentence explanation>"}`
    }],
    'You are a faithfulness judge. Evaluate if the answer is grounded in the provided context. Return only valid JSON with no markdown formatting.',
    200
  );
  try {
    const clean = result.replace(/```json|```/g, '').trim();
    const json = JSON.parse(clean.match(/\{[\s\S]*\}/)?.[0] || '{}');
    return { score: json.score ?? 75, verdict: json.verdict ?? 'Evaluation complete.' };
  } catch {
    return { score: 75, verdict: 'Could not parse faithfulness score.' };
  }
}

// ── Document Summarizer ───────────────────────────────────────
export async function summarizeDocument(name, text, apiKey) {
  const preview = text.slice(0, 6000); // limit context
  return await callGemini(
    apiKey,
    [{
      role: 'user',
      content: `Summarize the following document titled "${name}".\n\nProvide:\n1. A 2-3 sentence overview\n2. 3-5 key topics or main points (as bullet points)\n3. Any important terms or concepts\n\nDocument:\n${preview}`,
    }],
    'You are an expert document analyst. Create clear, concise summaries that capture the essence of documents. Use plain language.',
    512
  );
}

// ── Answer Summarizer ─────────────────────────────────────────
export async function summarizeAnswer(answer, apiKey) {
  if (answer.length < 200) return null; // short answers don't need a summary
  return await callGemini(
    apiKey,
    [{
      role: 'user',
      content: `Summarize the following answer in 1-2 sentences (TL;DR style):\n\n${answer}`,
    }],
    'You are a summarization assistant. Return only the concise TL;DR summary, nothing else.',
    128
  );
}

// ── Main pipeline entry point ─────────────────────────────────
export async function runRAGPipeline(query, store, apiKey, options = {}, callbacks = {}) {
  const {
    useHyde = true,
    useReranking = true,
    useFaithfulness = true,
  } = options;

  const {
    onStageStart = () => {},
    onStageComplete = () => {},
    onStreamChunk = () => {},
  } = callbacks;

  const trace = {};

  // ── L1: Query Rewriting ──
  onStageStart(1, 'Query Rewriting');
  const rewrittenQuery = await level1_queryRewrite(query, apiKey);
  trace.queryRewrite = { original: query, rewritten: rewrittenQuery };
  onStageComplete(1, trace.queryRewrite);

  // ── L2: HyDE ──
  let retrievalQuery = rewrittenQuery;
  if (useHyde) {
    onStageStart(2, 'HyDE Generation');
    const hypothetical = await level2_hyde(rewrittenQuery, apiKey);
    trace.hyde = { hypothetical };
    retrievalQuery = hypothetical;
    onStageComplete(2, trace.hyde);
  } else {
    onStageComplete(2, { skipped: true });
  }

  // ── L3: Hybrid Retrieval ──
  onStageStart(3, 'Hybrid Retrieval');
  const searchText = [query, rewrittenQuery, retrievalQuery].filter(Boolean).join(' ');
  const queryEmb = simpleEmbed([query, retrievalQuery].filter(Boolean).join(' '));
  const candidates = store.search(queryEmb, searchText, 12);
  trace.retrieval = {
    count: candidates.length,
    topChunks: candidates.slice(0, 3).map(c => ({
      source: c.source,
      score: c.hybridScore.toFixed(3),
      preview: c.text.slice(0, 100) + '...',
    })),
  };
  onStageComplete(3, trace.retrieval);

  // ── L4: Reranking ──
  let finalChunks = candidates;
  if (useReranking) {
    onStageStart(4, 'Reranking');
    finalChunks = await level4_rerank(rewrittenQuery, candidates, apiKey);
    trace.reranking = {
      before: candidates.slice(0, 3).map(c => c.source),
      after: finalChunks.slice(0, 3).map(c => c.source),
    };
    onStageComplete(4, trace.reranking);
  } else {
    onStageComplete(4, { skipped: true });
  }

  // ── L5: Grounded Generation ──
  onStageStart(5, 'Grounded Generation');
  const topChunks = finalChunks.slice(0, 5);
  let answer = '';
  if (topChunks.length === 0) {
    answer = 'I do not have enough information in the current knowledge base to answer that.';
    onStreamChunk(answer);
  } else {
    answer = await level5_generate(query, topChunks, apiKey, (partial) => {
      onStreamChunk(partial);
    });
  }
  trace.generation = { chunkCount: topChunks.length, answerLength: answer.length };
  onStageComplete(5, trace.generation);

  // ── L6: Faithfulness ──
  let faithfulness = null;
  if (useFaithfulness) {
    onStageStart(6, 'Faithfulness Check');
    faithfulness = await level6_faithfulness(answer, topChunks, apiKey);
    trace.faithfulness = faithfulness;
    onStageComplete(6, trace.faithfulness);
  } else {
    onStageComplete(6, { skipped: true });
  }

  return {
    answer,
    sources: topChunks,
    faithfulness,
    trace,
  };
}
